class AttrID:
    # Incomplete
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
