from _typeshed import Incomplete
from h5py._hl.base import HLObject

def __getattr__(name: str) -> Incomplete: ...

class Reference[T: HLObject]: ...
class RegionReference[T: HLObject](Reference[T]): ...
