from typing import Any

from h5py._base_id import BaseID

class TypeID(BaseID): ...

# TODO (these are C extension functions)
def check_dtype(*args: Any, **kwargs: Any) -> Any: ...
def check_enum_dtype(*args: Any, **kwargs: Any) -> Any: ...
def check_opaque_dtype(*args: Any, **kwargs: Any) -> Any: ...
def check_ref_dtype(*args: Any, **kwargs: Any) -> Any: ...
def check_string_dtype(*args: Any, **kwargs: Any) -> Any: ...
def check_vlen_dtype(*args: Any, **kwargs: Any) -> Any: ...
def enum_dtype(*args: Any, **kwargs: Any) -> Any: ...
def opaque_dtype(*args: Any, **kwargs: Any) -> Any: ...
def ref_dtype(*args: Any, **kwargs: Any) -> Any: ...
def regionref_dtype(*args: Any, **kwargs: Any) -> Any: ...
def special_dtype(*args: Any, **kwargs: Any) -> Any: ...
def string_dtype(*args: Any, **kwargs: Any) -> Any: ...
def vlen_dtype(*args: Any, **kwargs: Any) -> Any: ...
