from typing import Any

re_attr_match: Any
re_item_match: Any
re_object_match: Any

def h5py_item_completer(context: Any, command: Any) -> list[Any]: ...
def h5py_attr_completer(context: Any, command: Any) -> list[Any]: ...
def h5py_completer(self: Any, event: Any) -> list[Any]: ...
def load_ipython_extension(ip: Any = ...) -> None: ...
