"""
This type stub file was generated by pyright.
"""

"""
    Implements a portion of the selection operations.
"""

class ScalarReadSelection:
    """
    Implements slicing for scalar datasets.
    """
    def __init__(self, fspace, args) -> None: ...
    def __iter__(self):  # -> Generator[tuple[Any, Any], Any, None]:
        ...
