on:
  push:
    branches: ["*"]
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          version: 3.12
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.14
      - name: Install locked dependencies
        run: uv sync
      - name: Install latest type-checker dependencies
        run: uv pip install --upgrade basedpyright mypy pyright
      - name: Run mypy
        run: uv run mypy .
      - name: Run basedpyright
        run: uv run basedpyright
      - name: Configure pyright
        # basedpyright supports a "recommended" type checking mode, which is
        # similar to pyright's "strict" mode. Modify the option in
        # pyrightconfig.json to ensure pyright runs in strict mode.
        run: |
          sed -i \
            's/"typeCheckingMode": "recommended"/"typeCheckingMode": "strict"/' \
            pyrightconfig.json
          # Check that the file was changed
          ! git diff --exit-code pyrightconfig.json
      - name: Run pyright
        run: uv run pyright
